FROM rishabhpoddar/supertokens_android_sdk_testing

# Download Flutter SDK
RUN git clone https://github.com/flutter/flutter.git
ENV PATH "$PATH:/flutter/bin"
# Run basic check to download Dark SDK
RUN flutter doctor